import type {
  FixResult,
  FixStrategy,
  ValidationResult,
  AnalysedAlert,
  SecretFinding,
  AlertSeverity,
} from '../types.js';

// ─── Helpers ──────────────────────────────────────────────────────────────────

function severityEmoji(s: AlertSeverity): string {
  const map: Record<AlertSeverity, string> = {
    critical: '[CRITICAL]',
    high: '[HIGH]',
    medium: '[MEDIUM]',
    low: '[LOW]',
    info: '[INFO]',
  };
  return map[s];
}

function linkedAlertNumbers(strategy: FixStrategy): string {
  const nums: string[] = [];
  for (const [, numbers] of Object.entries(strategy.alert.githubAlertNumbers)) {
    if (Array.isArray(numbers)) {
      for (const n of numbers) nums.push(`#${n}`);
    }
  }
  return nums.join(', ') || '—';
}

function transitiveChainText(strategy: FixStrategy): string {
  if (!strategy.transitiveChain) return '—';
  const chain = strategy.transitiveChain.chain.map((n) => `${n.name}@${n.version}`);
  return chain.join(' → ');
}

// ─── Fix PR body ──────────────────────────────────────────────────────────────

export function buildFixPrBody(
  results: FixResult[],
  skipped: FixStrategy[],
  codeqlFindings: AnalysedAlert[],
  secretFindings: SecretFinding[],
  validation: ValidationResult | null
): string {
  const applied = results.filter((r) => r.applied);
  const rolledBack = results.filter((r) => r.rolledBack);

  const lines: string[] = [
    '## Security Fixes',
    '',
    `This PR was generated by [dep-guardian](https://github.com/rnataoliveira/dep-guardian) ` +
    `to address **${applied.length}** security vulnerabilit${applied.length === 1 ? 'y' : 'ies'}.`,
    '',
  ];

  // ── Applied fixes table
  if (applied.length > 0) {
    lines.push('### Fixes Applied', '');
    lines.push(
      '| Package | Was | Now | CVE / GHSA | Severity | Kind | Chain |',
      '|---------|-----|-----|-----------|----------|------|-------|'
    );
    for (const r of applied) {
      const s = r.strategy;
      lines.push(
        `| \`${s.targetPackage ?? '—'}\`` +
        ` | \`${s.currentSpecifier ?? '—'}\`` +
        ` | \`${s.proposedSpecifier ?? '—'}\`` +
        ` | ${s.alert.cve ?? s.alert.ghsaId ?? '—'}` +
        ` | ${severityEmoji(s.alert.severity)}` +
        ` | ${s.kind}` +
        ` | ${transitiveChainText(s)} |`
      );
    }
    lines.push('');

    // Linked alerts
    lines.push('### Linked Alerts', '');
    for (const r of applied) {
      for (const [, numbers] of Object.entries(r.strategy.alert.githubAlertNumbers)) {
        if (Array.isArray(numbers)) {
          for (const n of numbers) {
            lines.push(`- Closes #${n} — ${r.strategy.alert.summary}`);
          }
        }
      }
    }
    lines.push('');
  }

  // ── Rolled back
  if (rolledBack.length > 0) {
    lines.push('### Rolled Back (attempted but failed verification)', '');
    for (const r of rolledBack) {
      lines.push(`- \`${r.strategy.targetPackage}\`: ${r.error ?? 'unknown error'}`);
    }
    lines.push('');
  }

  // ── Skipped
  if (skipped.length > 0) {
    lines.push('### Skipped', '');
    lines.push('| Package | Reason |', '|---------|--------|');
    for (const s of skipped) {
      lines.push(`| \`${s.alert.packageName ?? s.alert.key}\` | ${s.skipReason ?? s.kind} |`);
    }
    lines.push('');
  }

  // ── CodeQL
  if (codeqlFindings.length > 0) {
    lines.push('### CodeQL Findings (manual review required)', '');
    for (const a of codeqlFindings) {
      for (const f of a.codeqlFindings ?? []) {
        lines.push(
          `- [${f.ruleName}](${f.url}) — \`${f.location.path}:${f.location.startLine}\` ${severityEmoji(f.severity)}`
        );
      }
    }
    lines.push('');
  }

  // ── Secrets
  if (secretFindings.length > 0) {
    lines.push('### Secret Scanning Findings (immediate action required)', '');
    lines.push('> **Warning:** Exposed secrets were detected. Revoke and rotate them immediately.');
    lines.push('');
    for (const s of secretFindings) {
      lines.push(`- [${s.secretTypeDisplay}](${s.url}) — Alert #${s.alertNumber}`);
    }
    lines.push('');
  }

  // ── Validation
  if (validation) {
    lines.push('### Validation', '');
    for (const step of validation.steps) {
      const icon = step.passed ? '- [x]' : '- [ ]';
      const duration = `(${(step.durationMs / 1000).toFixed(1)}s)`;
      lines.push(`${icon} \`${step.name}\` ${duration}`);
      if (!step.passed) {
        lines.push('  <details><summary>Output</summary>', '');
        lines.push('  ```');
        lines.push(step.output.split('\n').map((l) => `  ${l}`).join('\n'));
        lines.push('  ```');
        lines.push('  </details>', '');
      }
    }
    lines.push('');
  }

  lines.push('---');
  lines.push(`*Generated by dep-guardian on ${new Date().toISOString().slice(0, 10)}*`);

  return lines.join('\n');
}

// ─── Major bump issue body ─────────────────────────────────────────────────────

export function buildMajorBumpIssueBody(strategy: FixStrategy): string {
  const lines: string[] = [
    '## Major Version Update Required',
    '',
    `A security vulnerability in **${strategy.alert.packageName ?? '—'}** requires updating ` +
    `**${strategy.targetPackage}** from \`${strategy.currentSpecifier}\` to \`${strategy.proposedSpecifier}\` ` +
    `— a **${strategy.versionChangeType}** version bump.`,
    '',
    '### Vulnerability Details',
    '',
    `- **Severity:** ${severityEmoji(strategy.alert.severity)} ${strategy.alert.severity.toUpperCase()}`,
    `- **Summary:** ${strategy.alert.summary}`,
    `- **CVE/GHSA:** ${strategy.alert.cve ?? strategy.alert.ghsaId ?? 'N/A'}`,
    `- **Linked Alerts:** ${linkedAlertNumbers(strategy)}`,
    '',
  ];

  if (strategy.transitiveChain) {
    lines.push('### Dependency Chain', '');
    lines.push(`The vulnerability is in a transitive dependency:`);
    lines.push('');
    lines.push(`\`\`\`\n${transitiveChainText(strategy)}\n\`\`\``);
    lines.push('');
  }

  if (strategy.changelogExcerpt || strategy.migrationGuideUrl) {
    lines.push('### Migration Notes', '');
    if (strategy.migrationGuideUrl) {
      lines.push(`[View Changelog / Release Notes](${strategy.migrationGuideUrl})`);
      lines.push('');
    }
    if (strategy.changelogExcerpt) {
      lines.push('<details><summary>Changelog Excerpt</summary>', '');
      lines.push('```markdown');
      lines.push(strategy.changelogExcerpt);
      lines.push('```');
      lines.push('</details>', '');
    }
  }

  lines.push('### Action Required', '');
  lines.push(`1. Review the breaking changes in ${strategy.targetPackage} ${strategy.proposedVersion}`);
  lines.push(`2. Update \`${strategy.location?.section ?? 'dependencies'}\` in \`package.json\`:`);
  lines.push(`   \`"${strategy.targetPackage}": "${strategy.proposedSpecifier}"\``);
  lines.push('3. Run `npm install` and verify your application still works');
  lines.push('4. Run your test suite and lint before merging');
  lines.push('');
  lines.push('---');
  lines.push(`*Generated by dep-guardian on ${new Date().toISOString().slice(0, 10)}*`);

  return lines.join('\n');
}

// ─── PR title ─────────────────────────────────────────────────────────────────

export function buildPrTitle(fixCount: number, severities: AlertSeverity[]): string {
  const topSeverity = severities.includes('critical')
    ? 'critical'
    : severities.includes('high')
      ? 'high'
      : 'medium';

  return `fix(security): resolve ${fixCount} ${topSeverity} vulnerabilit${fixCount === 1 ? 'y' : 'ies'}`;
}

export function buildMajorBumpIssueTitle(strategy: FixStrategy): string {
  return `security: update ${strategy.targetPackage} to ${strategy.proposedVersion} (${strategy.alert.severity} severity)`;
}

export function buildBranchName(): string {
  const now = new Date();
  const ts = now.toISOString().replace(/[-:T.Z]/g, '').slice(0, 14);
  return `dep-guardian/${ts}`;
}
